version : '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db 
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    networks:
      - wp
    volumes:
      - wordpress:/var/www/html
    
  db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
        MYSQL_USER: exampleuser
        MYSQL_PASSWORD: examplepass
        MYSQL_DATABASE: exampledb
      networks:
        - wp
      volumes:
        - db:/var/lib/mysql

volumes:
  wordpress:
  db:

networks:
  wp:
    driver: bridge